import { useEffect, useMemo, useState } from "react";
import {
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  Trophy,
  Target,
  AlertOctagon,
  Repeat,
  CheckCircle2,
} from "lucide-react";
import { useExpenses } from "../../context/ExpenseContext";
import { generateInsights, generateAISummary } from "../../services/aiAdvisor";

const API_BASE = import.meta.env.VITE_API_BASE_URL || "http://localhost:5000";

const INSIGHT_ICONS = {
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "alert-triangle": AlertTriangle,
  "trophy": Trophy,
  "target": Target,
  "alert-octagon": AlertOctagon,
  "repeat": Repeat,
  "check-circle": CheckCircle2,
};

const SEVERITY_COLOR = {
  positive: "var(--income)",
  warning: "var(--budget-gold)",
  danger: "var(--expense)",
  info: "var(--accent-blue)",
};

export default function AIAdvisor() {
  const { expenses, income, budgets } = useExpenses();
  const insights = useMemo(() => generateInsights(expenses, income, budgets), [expenses, income, budgets]);
  const [llmSummary, setLlmSummary] = useState(null);
  const [loadingLlm, setLoadingLlm] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setLoadingLlm(true);
    generateAISummary(expenses, income, budgets, API_BASE).then((res) => {
      if (!cancelled) { setLlmSummary(res); setLoadingLlm(false); }
    });
    return () => { cancelled = true; };
  }, [expenses, income, budgets]);

  return (
    <div>
      <div className="page-header">
        <div>
          <div className="page-eyebrow">Smart insights</div>
          <h1>AI Advisor</h1>
        </div>
      </div>

      {loadingLlm && (
        <div className="panel card-pad text-muted" style={{ marginBottom: 20, fontSize: 13 }}>
          Checking for a live AI summary from your server…
        </div>
      )}
      {llmSummary && (
        <div className="panel card-pad" style={{ marginBottom: 20, borderColor: "var(--accent-blue)" }}>
          <div className="badge badge-gold" style={{ marginBottom: 12 }}>Generated by your connected AI model</div>
          <p style={{ lineHeight: 1.6, fontSize: 14 }}>{llmSummary}</p>
        </div>
      )}

      <div className="grid grid-2">
        {insights.map((ins, i) => {
          const IconComp = INSIGHT_ICONS[ins.icon] || Target;
          const color = SEVERITY_COLOR[ins.severity] || "var(--text-secondary)";
          return (
            <div key={i} className="panel card-pad" style={{ display: "flex", gap: 14 }}>
              <div
                style={{
                  width: 42, height: 42, borderRadius: 10, flexShrink: 0,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  background: "var(--bg-panel-raised)", color,
                }}
              >
                <IconComp size={22} />
              </div>
              <div>
                <div style={{ fontWeight: 700, marginBottom: 6 }}>{ins.title}</div>
                <div className="text-secondary" style={{ fontSize: 13, lineHeight: 1.5 }}>{ins.detail}</div>
              </div>
            </div>
          );
        })}
      </div>

      {!llmSummary && !loadingLlm && (
        <div className="panel card-pad text-muted" style={{ marginTop: 20, fontSize: 13 }}>
          These insights run entirely offline using a rule-based engine — no API key required.
          To get richer, natural-language analysis, add an AI key on the server (see <span className="mono">server/routes/aiRoutes.js</span>)
          and this panel will automatically upgrade.
        </div>
      )}
    </div>
  );
}
